- hosts: test
  remote_user: root
  tasks:
  - name: install httpd
    command: yum -y install httpd
  - name: provide httpd.conf
    copy : src="/root/httpd.conf" dest="/etc/httpd/conf/httpd.conf"
    tags: conf
    notify:
    - server restart
  - name: server start
    service: name=httpd state=started enabled=true
  handlers:
  - name: server restart
    service: name=httpd state=restarted
#tasks  hosts  remote_user handlers
#[{'tasks': [{'command': 'yum -y install httpd', 'name': 'install httpd'}, {'copy': 'src="/root/httpd.conf" dest="/etc/httpd/conf/httpd.conf"', 'notify': ['server restart'], 'tags': 'conf', 'name': 'provide httpd.conf'}, {'name': 'server start', 'service': 'name=httpd state=started enabled=true'}], 'hosts': 'test', 'remote_user': 'root', 'handlers': [{'name': 'server restart', 'service': 'name=httpd state=restarted'}]}]
