- hosts: all
  gather_facts: False
  vars:
  - my_var: "hello master master world"
    my_var2: "hangzhou"
  tasks:
  - name: test{{my_var}}
    shell: echo "aaaa{{my_var}} {{my_var2}}"
    register: var_result
  - debug: var=var_result
