/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.CarmackBusinessService;
import com.struts.form.CarmackBranchInfoForm;


/** 
 * MyEclipse Struts
 * Creation date: 08-16-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class CarmackBranchInfoAddAction extends Action {
	/*
	 * Generated Methods
	 */
	private CarmackBusinessService bs;
	
	public CarmackBusinessService getBs() {
		return bs;
	}

	public void setBs(CarmackBusinessService bs) {
		this.bs = bs;
	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取前台提交的数据信息
		
		String branchName=request.getParameter("BranchName");
		String branchLinkMan=request.getParameter("BranchLinkMan");
		String branchPhone=request.getParameter("BranchPhone");
		String branchAddress=request.getParameter("BranchAddress");
		String branchEmail=request.getParameter("BranchEmail");
		
		//将前台数据封装到UserInfoForm中
		CarmackBranchInfoForm ef= new CarmackBranchInfoForm();
		
		ef.setBranchName(branchName);
		ef.setBranchLinkMan(branchLinkMan);
		ef.setBranchPhone(branchPhone);
		ef.setBranchAddress(branchAddress);
		ef.setBranchEmail(branchEmail);
	
		
		//将UserInfoForm传递业务层处理
		boolean isok =  bs.getBranchinfobu().save(ef);
		
		request.setAttribute("biSaveState", isok);
		return mapping.findForward("bisave");
	}


}