/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.CarmackBusinessService;
import com.struts.form.CarmackBranchInfoForm;
import com.struts.form.CarmackUserInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class CarmackUserInfoUpdateAction extends Action {
	/*
	 * Generated Methods
	 */
	private CarmackBusinessService bs;
	

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取前台提交的数据信息
		String userID=request.getParameter("UserID");
		String userName=request.getParameter("UserName");
		String userRName=request.getParameter("UserRName");
		String userPhone=request.getParameter("UserPhone");
		String userLoginData=request.getParameter("UserLoginData");
		String userRegData=request.getParameter("UserRegData");
		String userPassWord=request.getParameter("UserPassWord");
		String userSex=request.getParameter("UserSex");
		String userCardID=request.getParameter("UserCardID");
		String userLoginNum=request.getParameter("UserLoginNum");
		String branchID=request.getParameter("BranchID");
		String departmentID=request.getParameter("DepartmentID");
		String roleID=request.getParameter("RoleID");
		
		//将前台数据封装到UserInfoForm中
		CarmackUserInfoForm ef= new CarmackUserInfoForm();
		ef.setUserID(userID);
		ef.setUserName(userName);
		ef.setUserRName(userRName);
		ef.setUserPhone(userPhone);
		ef.setUserLoginData(userLoginData);
		ef.setUserRegData(userRegData);
		ef.setUserPassword(userPassWord);
		ef.setUserSex(userSex);
		ef.setUserCardID(userCardID);
		ef.setUserLoginNum(userLoginNum);
		ef.setBranchID(branchID);
		ef.setDepartmentID(departmentID);
		ef.setRoleID(roleID);
		
		//将UserInfoForm传递业务层处理
		boolean isok =  bs.getUserinfobu().update(ef);
		
		request.setAttribute("uiUpdateState", isok);
		return mapping.findForward("UserInfoUpdate");
	}


	public CarmackBusinessService getBs() {
		return bs;
	}


	public void setBs(CarmackBusinessService bs) {
		this.bs = bs;
	}
}