/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.struts.form.MarsBillInfoForm;
import com.struts.form.MarsBranchInfoForm;
import com.struts.form.OptBranchInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2007
 * 
 * XDoclet definition:
 * @struts.action
 */
public class Mars_billinfo_getparamAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		OptBranchInfoForm billf=(OptBranchInfoForm)request.getSession(true).getAttribute("loginBranch");
		String branchid=billf.getBranchid();
		String cussendid=request.getParameter("cussendid");
		String billstartdata=request.getParameter("billstartdata");
		String billenddata=request.getParameter("billenddata"); 
		String billstateid=request.getParameter("billstateid");
		String sendbranch=request.getParameter("sendbranch");
		//选择公司查询  不选公司角色 选择货票状态
		if(sendbranch.equals("0")&&!billstateid.equals("9999")){
			request.setAttribute("branchid",branchid);
			request.setAttribute("billstateid", billstateid);
			request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			return mapping.findForward("listtwo");
		}
		//选择公司查询 不选公司角色 不选货票状态
	   if(sendbranch.equals("0")&&billstateid.equals("9999"))
		{
			System.out.println(billstartdata);
			System.out.println(billenddata);
		   request.setAttribute("branchid",branchid);
			request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			return mapping.findForward("listone");
		}
	   //选择公司查询 选择收货  不选货票状态
	   if(sendbranch.equals("1")&&billstateid.equals("9999")){
		   request.setAttribute("branchid",branchid);
		   request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			return mapping.findForward("listfive");
	   }
	   //选择公司查询 选择收货 选择货票状态
	   if(sendbranch.equals("1")&&!billstateid.equals("9999")){
		   request.setAttribute("branchid",branchid);
		   request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			request.setAttribute("billstateid", billstateid);
			return mapping.findForward("listsix");
	   }
	   //选择公司查询 选择发货  不选货票状态
	   if(sendbranch.equals("2")&&billstateid.equals("9999")){
		   request.setAttribute("branchid",branchid);
		   request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			return mapping.findForward("listthree");
	   }
	   //选择公司查询 选择发货 选择货票状态
	   if(sendbranch.equals("2")&&!billstateid.equals("9999")){
		   request.setAttribute("branchid",branchid);
		   request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			request.setAttribute("billstateid", billstateid);
			return mapping.findForward("listfour");
	   }
	   //选择客户查询 选择货票状态
		if(cussendid!=null&&!billstateid.equals("9999")){
			request.setAttribute("branchid",branchid);
			request.setAttribute("cussendid",cussendid);
			request.setAttribute("billstateid", billstateid);
			request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			return mapping.findForward("listeight");
		}
		//选择客户查询 不选择货票状态
		if(cussendid!=null&&billstateid.equals("9999")){
			request.setAttribute("branchid",branchid);
			request.setAttribute("cussendid",cussendid);
			request.setAttribute("billstartdata", billstartdata);
			request.setAttribute("billenddata", billenddata);
			return mapping.findForward("listseven");
		}
		//只选公司角色为收货 货票状态为1003
		if(sendbranch.equals("111")){
			request.setAttribute("branchid",branchid);
			request.setAttribute("billstateid", "1003");
			return mapping.findForward("listnine");
		}
		//只选公司角色为发货 货票状态为1003
		if(sendbranch.equals("222")){
			request.setAttribute("branchid",branchid);
			request.setAttribute("billstateid", "1003");
			return mapping.findForward("listten");
		}
		return null;
	}
}