/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.MosterBuService;
import com.struts.form.MosterBillInfoForm;
import com.struts.form.OptUserInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2008
 * 
 * XDoclet definition:
 * @struts.action path="/billupdateok" name="mosterBillInfoForm" scope="request"
 */
public class MoBillUpdateOkAction extends Action {
	/*
	 * Generated Methods
	 */
	private MosterBuService mobs;
	public MosterBuService getMobs() {
		return mobs;
	}
	public void setMobs(MosterBuService mobs) {
		this.mobs = mobs;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//获取从前台传来的表单数据
		String bid = request.getParameter("BillID");	
		String bsid = request.getParameter("BillStateID");
		String bmemo =request.getParameter("BillMemo");

		
		//获取当前登陆用户ID
		OptUserInfoForm ui = (OptUserInfoForm) request.getSession(true).getAttribute("loginer");
		String uid = ui.getUserid();
		
		MosterBillInfoForm mobi = new MosterBillInfoForm();
		mobi.setBillID(bid);
		mobi.setBillMemo(bmemo);
		mobi.setBillStateID(bsid);
		mobi.setUserID(uid);
		boolean isok = mobs.getMobillinfobuss().update(mobi);
		
		request.setAttribute("moBillUpdateState", isok);
		return mapping.findForward("mobillUpdateOK");
		
		
	}
}