/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.struts.form.MosterCargoInfoForm;
import com.service.*;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2008
 * 
 * XDoclet definition:
 * @struts.action path="/cargoinfoadd" name="mosterCargoInfoForm" input="/CargoAdd.jsp" scope="request"
 */
public class MoCargoInfoAddAction extends Action {
	/*
	 * Generated Methods
	 */
	private MosterBuService mobs;
	public MosterBuService getMobs() {
		return mobs;
	}
	public void setMobs(MosterBuService mobs) {
		this.mobs = mobs;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//获取前台提交的数据信息
		String cargoname = request.getParameter("CargoName");
		String cargoweight = request.getParameter("CargoWeight");
		String cargobulk = request.getParameter("CargoBulk");
		String cargonum = request.getParameter("CargoNum");
		String cargounit = request.getParameter("CargoUnit");
		String cargovalue = request.getParameter("CargoValue");
		String cargofreight = request.getParameter("CargoFreight");
		String cargoamends = request.getParameter("CargoAmends");
		String cargomemo = request.getParameter("CargoMemo");		
		String cargostate = request.getParameter("CargoState");
		String branchid = request.getParameter("BranchID");
		String cargostartdata = request.getParameter("CargoStartData");
		String cargoenddata = request.getParameter("CargoEndData");
		
		MosterCargoInfoForm mocif = new MosterCargoInfoForm();

		mocif.setCargoName(cargoname);
		mocif.setCargoWeight(cargoweight);
		mocif.setCargoBulk(cargobulk);
		mocif.setCargoNum(cargonum);
		mocif.setCargoUnit(cargounit);
		mocif.setCargoValue(cargovalue);
		mocif.setCargoFreight(cargofreight);
		mocif.setCargoAmends(cargoamends);
		mocif.setCargoMemo(cargomemo);
		mocif.setCargoState(cargostate);
		mocif.setBranchID(branchid);
		mocif.setCargoStartData(cargostartdata);
		mocif.setCargoEndData(cargoenddata);
		
		boolean isok = mobs.getMocargoinfobuss().save(mocif);
		request.setAttribute("ciAddState", isok);
		return mapping.findForward("mocargoadd");
		
	}
	
}