/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.MosterBuService;
import com.struts.form.MosterCargoInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class MoCargoSelectUpdateAction extends Action {
	/*
	 * Generated Methods
	 */
	private MosterBuService mobs;
	public MosterBuService getMobs() {
		return mobs;
	}
	public void setMobs(MosterBuService mobs) {
		this.mobs = mobs;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取前台提交的数据信息
		String cargoid = request.getParameter("CargoID");

		String cargoname = request.getParameter("CargoName");
		String cargoweight = request.getParameter("CargoWeight");
		String cargobulk = request.getParameter("CargoBulk");
		String cargonum = request.getParameter("CargoNum");
		String cargounit = request.getParameter("CargoUnit");
		String cargovalue = request.getParameter("CargoValue");
		String cargofreight = request.getParameter("CargoFreight");
		String cargoamends = request.getParameter("CargoAmends");
		String cargomemo = request.getParameter("CargoMemo");		
		String cargostate = request.getParameter("CargoState");
		String branchid = request.getParameter("BranchID");
		String cargostartdata = request.getParameter("CargoStartData");
		String cargoenddata = request.getParameter("CargoEndData");
		
		MosterCargoInfoForm mocif = new MosterCargoInfoForm();
		mocif.setCargoID(cargoid);
		mocif.setCargoName(cargoname);
		mocif.setCargoWeight(cargoweight);
		mocif.setCargoBulk(cargobulk);
		mocif.setCargoNum(cargonum);
		mocif.setCargoUnit(cargounit);
		mocif.setCargoValue(cargovalue);
		mocif.setCargoFreight(cargofreight);
		mocif.setCargoAmends(cargoamends);
		mocif.setCargoMemo(cargomemo);
		mocif.setCargoState(cargostate);
		mocif.setBranchID(branchid);
		mocif.setCargoStartData(cargostartdata);
		mocif.setCargoEndData(cargoenddata);
		
		boolean isok = mobs.getMocargoinfobuss().update(mocif);
		request.setAttribute("ciUpdateState", isok);
		return mapping.findForward("mocargoselectupdate");
	}
}