/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import java.util.*;
import com.service.MosterBuService;
import com.struts.form.MosterBillInfoForm;
import com.struts.form.MosterCargoInfoForm;
import com.struts.form.OptBranchInfoForm;
import com.struts.form.OptUserInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MoTraBillUpdateOkAction extends Action {
	/*
	 * Generated Methods
	 */
	private MosterBuService mobs;
	public MosterBuService getMobs() {
		return mobs;
	}
	public void setMobs(MosterBuService mobs) {
		this.mobs = mobs;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		//获取从前台传来的表单数据
		String bid = request.getParameter("BillID");	
		String bsid = request.getParameter("BillStateID");
		String bmemo =request.getParameter("BillMemo");

			
		
		//获取当前登陆用户ID
		OptUserInfoForm ui = (OptUserInfoForm) request.getSession(true).getAttribute("loginer");
		String uid = ui.getUserid();
		
		//获取当前登陆分公司
		OptBranchInfoForm bi = (OptBranchInfoForm) request.getSession(true).getAttribute("loginBranch");
		
		
		MosterBillInfoForm mobi = (MosterBillInfoForm) mobs.getMobillinfobuss().findById(bid);
		
		//获取该货票对应的所有的货物信息
		Vector cgvc = mobi.getCargos();
		for (int i = 0; i < cgvc.size(); i++) {
			//更新每一个货物的所属分公司编号，并修改状态为库存
			MosterCargoInfoForm ci = (MosterCargoInfoForm) cgvc.get(i);
			String cargostate = ci.getCargoState();
			ci.setCargoState("1");
			ci.setBranchID(bi.getBranchid());
			mobs.getMocargoinfobuss().update(ci);
		}
		
		mobi.setBillID(bid);
		mobi.setBillMemo(bmemo);
		mobi.setBillStateID(bsid);
		mobi.setUserID(uid);
		boolean isok = mobs.getMobillinfobuss().update(mobi);
		request.setAttribute("moBillUpdateState", isok);
		return mapping.findForward("motrabillupdate");
		
		
	}
}