/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import java.util.*;
import com.service.MosterBuService;
import com.struts.form.MosterBillInfoForm;
import com.struts.form.MosterCargoInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MoTraBillUpdateAction extends Action {
	/*
	 * Generated Methods
	 */
	private MosterBuService mobs;
	public MosterBuService getMobs() {
		return mobs;
	}
	public void setMobs(MosterBuService mobs) {
		this.mobs = mobs;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String id = request.getParameter("BillID");
		MosterBillInfoForm m = (MosterBillInfoForm) mobs.getMobillinfobuss().findById(id);
		Vector cargos =(Vector) m.getCargos();
//		MosterCargoInfoForm mc = (MosterCargoInfoForm) cargos.get(0);
		request.setAttribute("motracargoinfo", cargos);
		
		
		return mapping.findForward("motracargoByID");
	}
}