/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.json.*;
import com.service.OptBuService;
import com.struts.form.*;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class OptBillInfoListAction extends Action {
	/*
	 * Generated Methods
	 */
	//声明私有的OptBuService
	private OptBuService bus;

	public OptBuService getBus() {
		return bus;
	}

	public void setBus(OptBuService bus) {
		this.bus = bus;
	}
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取分页参数
		String start = request.getParameter("start");
		String limit = request.getParameter("limit");
		if (start == null) {
			start = "0";
		}
		if (limit == null) {
			limit = "10";
		}
		//将分页参数重新放置到域中
		request.setAttribute("start", start);
		request.setAttribute("limit", limit);
		
		//从Request获取BillInfoStateID
		String bisID=request.getParameter("BIStateID");
		
		//从Sessions中获取当前登陆分公司编号
		OptBranchInfoForm bi = (OptBranchInfoForm) request.getSession(true).getAttribute("loginBranch");
		
		Vector vc = new Vector();
		
		
		vc=bus.getBillbuss().findByBillStateID(new Integer(bisID),new Integer(bi.getBranchid()));

	
		request.setAttribute("BIvc", vc);
		
		return mapping.findForward("billinfo");
	}


}