/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.OptBuService;
import com.struts.form.OptBillInfoForm;
import com.struts.form.OptCargoInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class OptCargoFindByIDAction extends Action {
	/*
	 * Generated Methods
	 */
	//声明私有的OptBuService
	private OptBuService bus;
	
	public OptBuService getBus() {
		return bus;
	}

	public void setBus(OptBuService bus) {
		this.bus = bus;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//从request获取传来的BillInfoID
		String biID = request.getParameter("BillID");
	
		OptBillInfoForm biform = (OptBillInfoForm) bus.getBillbuss().findByID(biID);
		Vector cgvc = biform.getCargos();
		request.setAttribute("cargoByID", cgvc);
		
		return mapping.findForward("cargoByID");
	}


}