/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.OptBuService;
import com.struts.form.OptBranchInfoForm;
import com.struts.form.OptUserInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OptUserLoginAction extends Action {
	/*
	 * Generated Methods
	 */
	//声明私有的OptBuService
	private OptBuService bus;
	
	public OptBuService getBus() {
		return bus;
	}


	public void setBus(OptBuService bus) {
		this.bus = bus;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//接受前台Html页面传来的登陆数据
		String name=request.getParameter("username");
		String pass=request.getParameter("userpassword");
		String branchid=request.getParameter("branchid");

		//将登陆数据封装为ActionForm
		OptUserInfoForm uiform=new OptUserInfoForm();
		uiform.setUsername(name);
		uiform.setUserpassword(pass);
		uiform.setBranchid(branchid);
		
		//调用业务方法，验证登陆
		OptUserInfoForm rform=bus.getUserbuss().loginIsOK(uiform);
		if (rform!=null) {
			
			//将登陆用户的信息封装到Session作用域当中
			request.getSession(true).setAttribute("loginer", rform);
			
			//将所登录公司的信息封装到Session作用域中
			OptBranchInfoForm bf = (OptBranchInfoForm) bus.getBranchbuss().findByID(branchid);
			request.getSession(true).setAttribute("loginBranch", bf);
			
			request.setAttribute("loginMsg", "loginOK");
		}else{
			request.setAttribute("loginMsg", "loginFaile");
		}
		return mapping.findForward("msg");
	}

}