/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.Yasak_BusinessService;
import com.struts.form.OptBranchInfoForm;
import com.struts.form.Yasak_CustomerForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-20-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class Yasak_CustomerAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private Yasak_BusinessService ybs;

	public Yasak_BusinessService getYbs() {
		return ybs;
	}

	public void setYbs(Yasak_BusinessService ybs) {
		this.ybs = ybs;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取前台表单数据
		String customerName = request.getParameter("customerName");
		String customerLinkMan = request.getParameter("customerLinkMan");
		String customerSex = request.getParameter("customerSex");
		String customerPhone = request.getParameter("customerPhone");
		String customerFax = request.getParameter("customerFax");
		String customerPostId = request.getParameter("customerPostId");
		String customerEmail = request.getParameter("customerEmail");
		String customerRegData = request.getParameter("customerRegData");
		OptBranchInfoForm bi = (OptBranchInfoForm) request.getSession(true).getAttribute("loginBranch");
		String branchId = bi.getBranchid();
		//将数据封装
		Yasak_CustomerForm ycf = new Yasak_CustomerForm();
		ycf.setCustomerName(customerName);
		ycf.setCustomerLinkMan(customerLinkMan);
		ycf.setCustomerSex(customerSex);
		ycf.setCustomerPhone(customerPhone);
		ycf.setCustomerFax(customerFax);
		ycf.setCustomerPostId(customerPostId);
		ycf.setCustomerEmail(customerEmail);
		ycf.setCustomerRegData(customerRegData);
		ycf.setBranchId(branchId);
		
		boolean bl = ybs.getCustomerbu().save(ycf);
		request.setAttribute("Yasak_CustomerAdd", bl);
		return mapping.findForward("addok");
	}
}