/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;
import java.util.*;
import com.service.*;
import com.struts.form.OptBranchInfoForm;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class Yasak_CustomerListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private Yasak_BusinessService ybs;
	public Yasak_BusinessService getYbs() {
		return ybs;
	}
	public void setYbs(Yasak_BusinessService ybs) {
		this.ybs = ybs;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取分页参数
		String start =request.getParameter("start");
		String limit =request.getParameter("limit");
		if(start==null){
			start="0";
		}
		if (limit==null) {
			limit="10";
		}
		//将分页参数重新放置的域中
		request.setAttribute("yasak_start", start);
		request.setAttribute("yasak_limit", limit);
		OptBranchInfoForm bi = (OptBranchInfoForm) request.getSession(true).getAttribute("loginBranch");
		String str = bi.getBranchid();
		Vector vccus = ybs.getCustomerbu().findByBillAll(str);
		
		request.setAttribute("yasak_vccus", vccus);
		return mapping.findForward("list");
	}

}