/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.struts.form.*;
import com.service.Yasak_BusinessService;

/**
 * MyEclipse Struts Creation date: 08-18-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class Yasak_CustomerFindByIdAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private Yasak_BusinessService ybs;

	public Yasak_BusinessService getYbs() {
		return ybs;
	}

	public void setYbs(Yasak_BusinessService ybs) {
		this.ybs = ybs;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String cusId = request.getParameter("customerId");
		Yasak_CustomerForm ycf = (Yasak_CustomerForm) ybs.getCustomerbu()
				.findById(cusId);
		
		request.setAttribute("cusId", ycf);
		return mapping.findForward("findok");
	}
}