/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.service.Yasak_BusinessService;
import com.struts.form.*;

/** 
 * MyEclipse Struts
 * Creation date: 08-24-2008
 * 
 * XDoclet definition:
 * @struts.action
 */
public class Yasak_afficheAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private Yasak_BusinessService ybs;

	public Yasak_BusinessService getYbs() {
		return ybs;
	}

	public void setYbs(Yasak_BusinessService ybs) {
		this.ybs = ybs;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		OptUserInfoForm ui = (OptUserInfoForm) request.getSession(true).getAttribute("loginer");
		String userId = ui.getUserid();
		OptBranchInfoForm bi = (OptBranchInfoForm) request.getSession(true).getAttribute("loginBranch");
		String branchId = bi.getBranchid();
		//====================================
		String title = request.getParameter("title");
		String data = request.getParameter("data");
		String content = request.getParameter("content");
		
		Yasak_AfficheInfoForm yaf = new Yasak_AfficheInfoForm();
		yaf.setUserId(userId);
		yaf.setAfficheTitle(title);
		yaf.setAfficheData(data);
		yaf.setAfficheContent(content);
		yaf.setBranchId(branchId);
		
		boolean bl = ybs.getAibu().save(yaf);
		request.setAttribute("Yasak_AfficheAdd", bl);
		return mapping.findForward("addok");
	}
}