/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="carmackBranchInfoForm"
 */
public class CarmackBranchInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchID property */
	private String branchID;

	/** branchName property */
	private String branchName;

	/** branchEmail property */
	private String branchEmail;

	/** branchLinkMan property */
	private String branchLinkMan;

	/** branchAddress property */
	private String branchAddress;

	/** branchPhone property */
	private String branchPhone;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchID.
	 * @return String
	 */
	public String getBranchID() {
		return branchID;
	}

	/** 
	 * Set the branchID.
	 * @param branchID The branchID to set
	 */
	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	/** 
	 * Returns the branchName.
	 * @return String
	 */
	public String getBranchName() {
		return branchName;
	}

	/** 
	 * Set the branchName.
	 * @param branchName The branchName to set
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	/** 
	 * Returns the branchEmail.
	 * @return String
	 */
	public String getBranchEmail() {
		return branchEmail;
	}

	/** 
	 * Set the branchEmail.
	 * @param branchEmail The branchEmail to set
	 */
	public void setBranchEmail(String branchEmail) {
		this.branchEmail = branchEmail;
	}

	/** 
	 * Returns the branchLinkMan.
	 * @return String
	 */
	public String getBranchLinkMan() {
		return branchLinkMan;
	}

	/** 
	 * Set the branchLinkMan.
	 * @param branchLinkMan The branchLinkMan to set
	 */
	public void setBranchLinkMan(String branchLinkMan) {
		this.branchLinkMan = branchLinkMan;
	}

	/** 
	 * Returns the branchAddress.
	 * @return String
	 */
	public String getBranchAddress() {
		return branchAddress;
	}

	/** 
	 * Set the branchAddress.
	 * @param branchAddress The branchAddress to set
	 */
	public void setBranchAddress(String branchAddress) {
		this.branchAddress = branchAddress;
	}

	/** 
	 * Returns the branchPhone.
	 * @return String
	 */
	public String getBranchPhone() {
		return branchPhone;
	}

	/** 
	 * Set the branchPhone.
	 * @param branchPhone The branchPhone to set
	 */
	public void setBranchPhone(String branchPhone) {
		this.branchPhone = branchPhone;
	}
}