/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import java.util.Vector;
/** 
 * MyEclipse Struts
 * Creation date: 08-20-2008
 * 
 * XDoclet definition:
 * @struts.form name="carmackSystemLogForm"
 */
public class CarmackSystemLogForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchID property */
	private String branchID;

	/** userID property */
	private String userID;

	/** systemLogID property */
	private String systemLogID;

	/** systemLogMemo property */
	private String systemLogMemo;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}
	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchID.
	 * @return String
	 */
	public String getBranchID() {
		return branchID;
	}

	/** 
	 * Set the branchID.
	 * @param branchID The branchID to set
	 */
	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	/** 
	 * Returns the userID.
	 * @return String
	 */
	public String getUserID() {
		return userID;
	}

	/** 
	 * Set the userID.
	 * @param userID The userID to set
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/** 
	 * Returns the systemLogID.
	 * @return String
	 */
	public String getSystemLogID() {
		return systemLogID;
	}

	/** 
	 * Set the systemLogID.
	 * @param systemLogID The systemLogID to set
	 */
	public void setSystemLogID(String systemLogID) {
		this.systemLogID = systemLogID;
	}

	/** 
	 * Returns the systemLogMemo.
	 * @return String
	 */
	public String getSystemLogMemo() {
		return systemLogMemo;
	}

	/** 
	 * Set the systemLogMemo.
	 * @param systemLogMemo The systemLogMemo to set
	 */
	public void setSystemLogMemo(String systemLogMemo) {
		this.systemLogMemo = systemLogMemo;
	}
	
}