/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="carmackUserInfoForm"
 */
public class CarmackUserInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userCardID property */
	private String userCardID;

	/** userRegData property */
	private String userRegData;

	/** userName property */
	private String userName;

	/** userLoginData property */
	private String userLoginData;

	/** userID property */
	private String userID;

	/** departmentID property */
	private String departmentID;

	/** userPassword property */
	private String userPassword;

	/** roleID property */
	private String roleID;

	/** branchID property */
	private String branchID;

	/** userSex property */
	private String userSex;

	/** userPhone property */
	private String userPhone;

	/** userRName property */
	private String userRName;

	/** userLoginNum property */
	private String userLoginNum;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userCardID.
	 * @return String
	 */
	public String getUserCardID() {
		return userCardID;
	}

	/** 
	 * Set the userCardID.
	 * @param userCardID The userCardID to set
	 */
	public void setUserCardID(String userCardID) {
		this.userCardID = userCardID;
	}

	/** 
	 * Returns the userRegData.
	 * @return String
	 */
	public String getUserRegData() {
		return userRegData;
	}

	/** 
	 * Set the userRegData.
	 * @param userRegData The userRegData to set
	 */
	public void setUserRegData(String userRegData) {
		this.userRegData = userRegData;
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the userLoginData.
	 * @return String
	 */
	public String getUserLoginData() {
		return userLoginData;
	}

	/** 
	 * Set the userLoginData.
	 * @param userLoginData The userLoginData to set
	 */
	public void setUserLoginData(String userLoginData) {
		this.userLoginData = userLoginData;
	}

	/** 
	 * Returns the userID.
	 * @return String
	 */
	public String getUserID() {
		return userID;
	}

	/** 
	 * Set the userID.
	 * @param userID The userID to set
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/** 
	 * Returns the departmentID.
	 * @return String
	 */
	public String getDepartmentID() {
		return departmentID;
	}

	/** 
	 * Set the departmentID.
	 * @param departmentID The departmentID to set
	 */
	public void setDepartmentID(String departmentID) {
		this.departmentID = departmentID;
	}

	/** 
	 * Returns the userPassword.
	 * @return String
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/** 
	 * Set the userPassword.
	 * @param userPassword The userPassword to set
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/** 
	 * Returns the roleID.
	 * @return String
	 */
	public String getRoleID() {
		return roleID;
	}

	/** 
	 * Set the roleID.
	 * @param roleID The roleID to set
	 */
	public void setRoleID(String roleID) {
		this.roleID = roleID;
	}

	/** 
	 * Returns the branchID.
	 * @return String
	 */
	public String getBranchID() {
		return branchID;
	}

	/** 
	 * Set the branchID.
	 * @param branchID The branchID to set
	 */
	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	/** 
	 * Returns the userSex.
	 * @return String
	 */
	public String getUserSex() {
		return userSex;
	}

	/** 
	 * Set the userSex.
	 * @param userSex The userSex to set
	 */
	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	/** 
	 * Returns the userPhone.
	 * @return String
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/** 
	 * Set the userPhone.
	 * @param userPhone The userPhone to set
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/** 
	 * Returns the userRName.
	 * @return String
	 */
	public String getUserRName() {
		return userRName;
	}

	/** 
	 * Set the userRName.
	 * @param userRName The userRName to set
	 */
	public void setUserRName(String userRName) {
		this.userRName = userRName;
	}

	/** 
	 * Returns the userLoginNum.
	 * @return String
	 */
	public String getUserLoginNum() {
		return userLoginNum;
	}

	/** 
	 * Set the userLoginNum.
	 * @param userLoginNum The userLoginNum to set
	 */
	public void setUserLoginNum(String userLoginNum) {
		this.userLoginNum = userLoginNum;
	}
}