/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="carmackTruckLogForm"
 */
public class CarmackTruckLogForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchID property */
	private String branchID;

	/** tLStartData property */
	private String tLStartData;

	/** tLID property */
	private String tLID;

	/** dirverID property */
	private String dirverID;

	/** tLArrive property */
	private String tLArrive;

	/** truckID property */
	private String truckID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchID.
	 * @return String
	 */
	public String getBranchID() {
		return branchID;
	}

	/** 
	 * Set the branchID.
	 * @param branchID The branchID to set
	 */
	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	/** 
	 * Returns the tLStartData.
	 * @return String
	 */
	public String getTLStartData() {
		return tLStartData;
	}

	/** 
	 * Set the tLStartData.
	 * @param tLStartData The tLStartData to set
	 */
	public void setTLStartData(String tLStartData) {
		this.tLStartData = tLStartData;
	}

	/** 
	 * Returns the tLID.
	 * @return String
	 */
	public String getTLID() {
		return tLID;
	}

	/** 
	 * Set the tLID.
	 * @param tLID The tLID to set
	 */
	public void setTLID(String tLID) {
		this.tLID = tLID;
	}

	/** 
	 * Returns the dirverID.
	 * @return String
	 */
	public String getDirverID() {
		return dirverID;
	}

	/** 
	 * Set the dirverID.
	 * @param dirverID The dirverID to set
	 */
	public void setDirverID(String dirverID) {
		this.dirverID = dirverID;
	}

	/** 
	 * Returns the tLArrive.
	 * @return String
	 */
	public String getTLArrive() {
		return tLArrive;
	}

	/** 
	 * Set the tLArrive.
	 * @param tLArrive The tLArrive to set
	 */
	public void setTLArrive(String tLArrive) {
		this.tLArrive = tLArrive;
	}

	/** 
	 * Returns the truckID.
	 * @return String
	 */
	public String getTruckID() {
		return truckID;
	}

	/** 
	 * Set the truckID.
	 * @param truckID The truckID to set
	 */
	public void setTruckID(String truckID) {
		this.truckID = truckID;
	}
}