/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="carmackTruckInfoForm"
 */
public class CarmackTruckInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchID property */
	private String branchID;
	
	/** branchName property */
	private String branchName;

	/** truckBuyData property */
	private String truckBuyData;

	/** truckPhoto property */
	private String truckPhoto;

	/** truckInsuranceNum property */
	private String truckInsuranceNum;

	/** truckRunNum property */
	private String truckRunNum;

	/** truckNum property */
	private String truckNum;

	/** truckEngineNum property */
	private String truckEngineNum;

	/** truckColor property */
	private String truckColor;

	/** bruckIsVacancy property */
	private String bruckIsVacancy;

	/** tMID property */
	private String tMID;

	/** truckID property */
	private String truckID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchID.
	 * @return String
	 */
	public String getBranchID() {
		return branchID;
	}

	/** 
	 * Set the branchID.
	 * @param branchID The branchID to set
	 */
	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	/** 
	 * Returns the truckBuyData.
	 * @return String
	 */
	public String getTruckBuyData() {
		return truckBuyData;
	}

	/** 
	 * Set the truckBuyData.
	 * @param truckBuyData The truckBuyData to set
	 */
	public void setTruckBuyData(String truckBuyData) {
		this.truckBuyData = truckBuyData;
	}

	/** 
	 * Returns the truckPhoto.
	 * @return String
	 */
	public String getTruckPhoto() {
		return truckPhoto;
	}

	/** 
	 * Set the truckPhoto.
	 * @param truckPhoto The truckPhoto to set
	 */
	public void setTruckPhoto(String truckPhoto) {
		this.truckPhoto = truckPhoto;
	}

	/** 
	 * Returns the truckInsuranceNum.
	 * @return String
	 */
	public String getTruckInsuranceNum() {
		return truckInsuranceNum;
	}

	/** 
	 * Set the truckInsuranceNum.
	 * @param truckInsuranceNum The truckInsuranceNum to set
	 */
	public void setTruckInsuranceNum(String truckInsuranceNum) {
		this.truckInsuranceNum = truckInsuranceNum;
	}

	/** 
	 * Returns the truckRunNum.
	 * @return String
	 */
	public String getTruckRunNum() {
		return truckRunNum;
	}

	/** 
	 * Set the truckRunNum.
	 * @param truckRunNum The truckRunNum to set
	 */
	public void setTruckRunNum(String truckRunNum) {
		this.truckRunNum = truckRunNum;
	}

	/** 
	 * Returns the truckNum.
	 * @return String
	 */
	public String getTruckNum() {
		return truckNum;
	}

	/** 
	 * Set the truckNum.
	 * @param truckNum The truckNum to set
	 */
	public void setTruckNum(String truckNum) {
		this.truckNum = truckNum;
	}

	/** 
	 * Returns the truckEngineNum.
	 * @return String
	 */
	public String getTruckEngineNum() {
		return truckEngineNum;
	}

	/** 
	 * Set the truckEngineNum.
	 * @param truckEngineNum The truckEngineNum to set
	 */
	public void setTruckEngineNum(String truckEngineNum) {
		this.truckEngineNum = truckEngineNum;
	}

	/** 
	 * Returns the truckColor.
	 * @return String
	 */
	public String getTruckColor() {
		return truckColor;
	}

	/** 
	 * Set the truckColor.
	 * @param truckColor The truckColor to set
	 */
	public void setTruckColor(String truckColor) {
		this.truckColor = truckColor;
	}

	/** 
	 * Returns the bruckIsVacancy.
	 * @return String
	 */
	public String getBruckIsVacancy() {
		return bruckIsVacancy;
	}

	/** 
	 * Set the bruckIsVacancy.
	 * @param bruckIsVacancy The bruckIsVacancy to set
	 */
	public void setBruckIsVacancy(String bruckIsVacancy) {
		this.bruckIsVacancy = bruckIsVacancy;
	}

	/** 
	 * Returns the tMID.
	 * @return String
	 */
	public String getTMID() {
		return tMID;
	}

	/** 
	 * Set the tMID.
	 * @param tMID The tMID to set
	 */
	public void setTMID(String tMID) {
		this.tMID = tMID;
	}

	/** 
	 * Returns the truckID.
	 * @return String
	 */
	public String getTruckID() {
		return truckID;
	}

	/** 
	 * Set the truckID.
	 * @param truckID The truckID to set
	 */
	public void setTruckID(String truckID) {
		this.truckID = truckID;
	}

	/** 
	 * Returns the branchName.
	 * @return String
	 */
	public String getBranchName() {
		return branchName;
	}

	/** 
	 * Set the branchName.
	 * @param truckID The branchName to set
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}
}