/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="marsTruckLogForm"
 */
public class MarsTruckLogForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** tlstartdata property */
	private String tlstartdata;

	/** truckid property */
	private String truckid;

	/** tlarrive property */
	private String tlarrive;

	/** driverid property */
	private String driverid;

	/** drivername property */
	private String drivername;

	/** tlid property */
	private String tlid;

	/** branchid property */
	private String branchid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the tlstartdata.
	 * @return String
	 */
	public String getTlstartdata() {
		return tlstartdata;
	}

	/** 
	 * Set the tlstartdata.
	 * @param tlstartdata The tlstartdata to set
	 */
	public void setTlstartdata(String tlstartdata) {
		this.tlstartdata = tlstartdata;
	}

	/** 
	 * Returns the truckid.
	 * @return String
	 */
	public String getTruckid() {
		return truckid;
	}

	/** 
	 * Set the truckid.
	 * @param truckid The truckid to set
	 */
	public void setTruckid(String truckid) {
		this.truckid = truckid;
	}

	/** 
	 * Returns the tlarrive.
	 * @return String
	 */
	public String getTlarrive() {
		return tlarrive;
	}

	/** 
	 * Set the tlarrive.
	 * @param tlarrive The tlarrive to set
	 */
	public void setTlarrive(String tlarrive) {
		this.tlarrive = tlarrive;
	}

	/** 
	 * Returns the driverid.
	 * @return String
	 */
	public String getDriverid() {
		return driverid;
	}

	/** 
	 * Set the driverid.
	 * @param driverid The driverid to set
	 */
	public void setDriverid(String driverid) {
		this.driverid = driverid;
	}

	/** 
	 * Returns the drivername.
	 * @return String
	 */
	public String getDrivername() {
		return drivername;
	}

	/** 
	 * Set the drivername.
	 * @param drivername The drivername to set
	 */
	public void setDrivername(String drivername) {
		this.drivername = drivername;
	}

	/** 
	 * Returns the tlid.
	 * @return String
	 */
	public String getTlid() {
		return tlid;
	}

	/** 
	 * Set the tlid.
	 * @param tlid The tlid to set
	 */
	public void setTlid(String tlid) {
		this.tlid = tlid;
	}

	/** 
	 * Returns the branchid.
	 * @return String
	 */
	public String getBranchid() {
		return branchid;
	}

	/** 
	 * Set the branchid.
	 * @param branchid The branchid to set
	 */
	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}
}