/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-27-2008
 * 
 * XDoclet definition:
 * @struts.form name="marsJfreeCharFormForm"
 */
public class MarsJfreeCharFormForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** count property */
	private String count;

	/** sendid property */
	private String sendid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the count.
	 * @return String
	 */
	public String getCount() {
		return count;
	}

	/** 
	 * Set the count.
	 * @param count The count to set
	 */
	public void setCount(String count) {
		this.count = count;
	}

	/** 
	 * Returns the sendid.
	 * @return String
	 */
	public String getSendid() {
		return sendid;
	}

	/** 
	 * Set the sendid.
	 * @param sendid The sendid to set
	 */
	public void setSendid(String sendid) {
		this.sendid = sendid;
	}
}