/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="marsUserInfoForm"
 */
public class MarsUserInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** departmendid property */
	private String departmendid;

	/** userrolename property */
	private String userrolename;

	/** usersex property */
	private String usersex;

	/** userpassword property */
	private String userpassword;

	/** userphone property */
	private String userphone;

	/** usercardid property */
	private String usercardid;

	/** userid property */
	private String userid;

	/** userloginnum property */
	private String userloginnum;

	/** departmentname property */
	private String departmentname;

	/** userrname property */
	private String userrname;

	/** username property */
	private String username;

	/** userregdata property */
	private String userregdata;

	/** roleid property */
	private String roleid;

	/** userlogindata property */
	private String userlogindata;

	/** branchid property */
	private String branchid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the departmendid.
	 * @return String
	 */
	public String getDepartmendid() {
		return departmendid;
	}

	/** 
	 * Set the departmendid.
	 * @param departmendid The departmendid to set
	 */
	public void setDepartmendid(String departmendid) {
		this.departmendid = departmendid;
	}

	/** 
	 * Returns the userrolename.
	 * @return String
	 */
	public String getUserrolename() {
		return userrolename;
	}

	/** 
	 * Set the userrolename.
	 * @param userrolename The userrolename to set
	 */
	public void setUserrolename(String userrolename) {
		this.userrolename = userrolename;
	}

	/** 
	 * Returns the usersex.
	 * @return String
	 */
	public String getUsersex() {
		return usersex;
	}

	/** 
	 * Set the usersex.
	 * @param usersex The usersex to set
	 */
	public void setUsersex(String usersex) {
		this.usersex = usersex;
	}

	/** 
	 * Returns the userpassword.
	 * @return String
	 */
	public String getUserpassword() {
		return userpassword;
	}

	/** 
	 * Set the userpassword.
	 * @param userpassword The userpassword to set
	 */
	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	/** 
	 * Returns the userphone.
	 * @return String
	 */
	public String getUserphone() {
		return userphone;
	}

	/** 
	 * Set the userphone.
	 * @param userphone The userphone to set
	 */
	public void setUserphone(String userphone) {
		this.userphone = userphone;
	}

	/** 
	 * Returns the usercardid.
	 * @return String
	 */
	public String getUsercardid() {
		return usercardid;
	}

	/** 
	 * Set the usercardid.
	 * @param usercardid The usercardid to set
	 */
	public void setUsercardid(String usercardid) {
		this.usercardid = usercardid;
	}

	/** 
	 * Returns the userid.
	 * @return String
	 */
	public String getUserid() {
		return userid;
	}

	/** 
	 * Set the userid.
	 * @param userid The userid to set
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/** 
	 * Returns the userloginnum.
	 * @return String
	 */
	public String getUserloginnum() {
		return userloginnum;
	}

	/** 
	 * Set the userloginnum.
	 * @param userloginnum The userloginnum to set
	 */
	public void setUserloginnum(String userloginnum) {
		this.userloginnum = userloginnum;
	}

	/** 
	 * Returns the departmentname.
	 * @return String
	 */
	public String getDepartmentname() {
		return departmentname;
	}

	/** 
	 * Set the departmentname.
	 * @param departmentname The departmentname to set
	 */
	public void setDepartmentname(String departmentname) {
		this.departmentname = departmentname;
	}

	/** 
	 * Returns the userrname.
	 * @return String
	 */
	public String getUserrname() {
		return userrname;
	}

	/** 
	 * Set the userrname.
	 * @param userrname The userrname to set
	 */
	public void setUserrname(String userrname) {
		this.userrname = userrname;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the userregdata.
	 * @return String
	 */
	public String getUserregdata() {
		return userregdata;
	}

	/** 
	 * Set the userregdata.
	 * @param userregdata The userregdata to set
	 */
	public void setUserregdata(String userregdata) {
		this.userregdata = userregdata;
	}

	/** 
	 * Returns the roleid.
	 * @return String
	 */
	public String getRoleid() {
		return roleid;
	}

	/** 
	 * Set the roleid.
	 * @param roleid The roleid to set
	 */
	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	/** 
	 * Returns the userlogindata.
	 * @return String
	 */
	public String getUserlogindata() {
		return userlogindata;
	}

	/** 
	 * Set the userlogindata.
	 * @param userlogindata The userlogindata to set
	 */
	public void setUserlogindata(String userlogindata) {
		this.userlogindata = userlogindata;
	}

	/** 
	 * Returns the branchid.
	 * @return String
	 */
	public String getBranchid() {
		return branchid;
	}

	/** 
	 * Set the branchid.
	 * @param branchid The branchid to set
	 */
	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}
}