/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="marsCargoInfoForm"
 */
public class MarsCargoInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cargoname property */
	private String cargoname;

	/** cargostartdata property */
	private String cargostartdata;

	/** branchname property */
	private String branchname;

	/** cargoweight property */
	private String cargoweight;

	/** cargoid property */
	private String cargoid;

	/** cargoenddata property */
	private String cargoenddata;

	/** cargofreight property */
	private String cargofreight;

	/** cargoamends property */
	private String cargoamends;

	/** cargobulk property */
	private String cargobulk;

	/** cargomemo property */
	private String cargomemo;

	/** cargounit property */
	private String cargounit;

	/** cargostate property */
	private String cargostate;

	/** branchid property */
	private String branchid;

	/** cargovalue property */
	private String cargovalue;

	/** cargonum property */
	private String cargonum;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cargoname.
	 * @return String
	 */
	public String getCargoname() {
		return cargoname;
	}

	/** 
	 * Set the cargoname.
	 * @param cargoname The cargoname to set
	 */
	public void setCargoname(String cargoname) {
		this.cargoname = cargoname;
	}

	/** 
	 * Returns the cargostartdata.
	 * @return String
	 */
	public String getCargostartdata() {
		return cargostartdata;
	}

	/** 
	 * Set the cargostartdata.
	 * @param cargostartdata The cargostartdata to set
	 */
	public void setCargostartdata(String cargostartdata) {
		this.cargostartdata = cargostartdata;
	}

	/** 
	 * Returns the branchname.
	 * @return String
	 */
	public String getBranchname() {
		return branchname;
	}

	/** 
	 * Set the branchname.
	 * @param branchname The branchname to set
	 */
	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}

	/** 
	 * Returns the cargoweight.
	 * @return String
	 */
	public String getCargoweight() {
		return cargoweight;
	}

	/** 
	 * Set the cargoweight.
	 * @param cargoweight The cargoweight to set
	 */
	public void setCargoweight(String cargoweight) {
		this.cargoweight = cargoweight;
	}

	/** 
	 * Returns the cargoid.
	 * @return String
	 */
	public String getCargoid() {
		return cargoid;
	}

	/** 
	 * Set the cargoid.
	 * @param cargoid The cargoid to set
	 */
	public void setCargoid(String cargoid) {
		this.cargoid = cargoid;
	}

	/** 
	 * Returns the cargoenddata.
	 * @return String
	 */
	public String getCargoenddata() {
		return cargoenddata;
	}

	/** 
	 * Set the cargoenddata.
	 * @param cargoenddata The cargoenddata to set
	 */
	public void setCargoenddata(String cargoenddata) {
		this.cargoenddata = cargoenddata;
	}

	/** 
	 * Returns the cargofreight.
	 * @return String
	 */
	public String getCargofreight() {
		return cargofreight;
	}

	/** 
	 * Set the cargofreight.
	 * @param cargofreight The cargofreight to set
	 */
	public void setCargofreight(String cargofreight) {
		this.cargofreight = cargofreight;
	}

	/** 
	 * Returns the cargoamends.
	 * @return String
	 */
	public String getCargoamends() {
		return cargoamends;
	}

	/** 
	 * Set the cargoamends.
	 * @param cargoamends The cargoamends to set
	 */
	public void setCargoamends(String cargoamends) {
		this.cargoamends = cargoamends;
	}

	/** 
	 * Returns the cargobulk.
	 * @return String
	 */
	public String getCargobulk() {
		return cargobulk;
	}

	/** 
	 * Set the cargobulk.
	 * @param cargobulk The cargobulk to set
	 */
	public void setCargobulk(String cargobulk) {
		this.cargobulk = cargobulk;
	}

	/** 
	 * Returns the cargomemo.
	 * @return String
	 */
	public String getCargomemo() {
		return cargomemo;
	}

	/** 
	 * Set the cargomemo.
	 * @param cargomemo The cargomemo to set
	 */
	public void setCargomemo(String cargomemo) {
		this.cargomemo = cargomemo;
	}

	/** 
	 * Returns the cargounit.
	 * @return String
	 */
	public String getCargounit() {
		return cargounit;
	}

	/** 
	 * Set the cargounit.
	 * @param cargounit The cargounit to set
	 */
	public void setCargounit(String cargounit) {
		this.cargounit = cargounit;
	}

	/** 
	 * Returns the cargostate.
	 * @return String
	 */
	public String getCargostate() {
		return cargostate;
	}

	/** 
	 * Set the cargostate.
	 * @param cargostate The cargostate to set
	 */
	public void setCargostate(String cargostate) {
		this.cargostate = cargostate;
	}

	/** 
	 * Returns the branchid.
	 * @return String
	 */
	public String getBranchid() {
		return branchid;
	}

	/** 
	 * Set the branchid.
	 * @param branchid The branchid to set
	 */
	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}

	/** 
	 * Returns the cargovalue.
	 * @return String
	 */
	public String getCargovalue() {
		return cargovalue;
	}

	/** 
	 * Set the cargovalue.
	 * @param cargovalue The cargovalue to set
	 */
	public void setCargovalue(String cargovalue) {
		this.cargovalue = cargovalue;
	}

	/** 
	 * Returns the cargonum.
	 * @return String
	 */
	public String getCargonum() {
		return cargonum;
	}

	/** 
	 * Set the cargonum.
	 * @param cargonum The cargonum to set
	 */
	public void setCargonum(String cargonum) {
		this.cargonum = cargonum;
	}
}