/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="marsBranchInfoForm"
 */
public class MarsBranchInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchaddress property */
	private String branchaddress;

	/** branchname property */
	private String branchname;

	/** branchemail property */
	private String branchemail;

	/** branchphone property */
	private String branchphone;

	/** branchlinkman property */
	private String branchlinkman;

	/** branchid property */
	private String branchid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchaddress.
	 * @return String
	 */
	public String getBranchaddress() {
		return branchaddress;
	}

	/** 
	 * Set the branchaddress.
	 * @param branchaddress The branchaddress to set
	 */
	public void setBranchaddress(String branchaddress) {
		this.branchaddress = branchaddress;
	}

	/** 
	 * Returns the branchname.
	 * @return String
	 */
	public String getBranchname() {
		return branchname;
	}

	/** 
	 * Set the branchname.
	 * @param branchname The branchname to set
	 */
	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}

	/** 
	 * Returns the branchemail.
	 * @return String
	 */
	public String getBranchemail() {
		return branchemail;
	}

	/** 
	 * Set the branchemail.
	 * @param branchemail The branchemail to set
	 */
	public void setBranchemail(String branchemail) {
		this.branchemail = branchemail;
	}

	/** 
	 * Returns the branchphone.
	 * @return String
	 */
	public String getBranchphone() {
		return branchphone;
	}

	/** 
	 * Set the branchphone.
	 * @param branchphone The branchphone to set
	 */
	public void setBranchphone(String branchphone) {
		this.branchphone = branchphone;
	}

	/** 
	 * Returns the branchlinkman.
	 * @return String
	 */
	public String getBranchlinkman() {
		return branchlinkman;
	}

	/** 
	 * Set the branchlinkman.
	 * @param branchlinkman The branchlinkman to set
	 */
	public void setBranchlinkman(String branchlinkman) {
		this.branchlinkman = branchlinkman;
	}

	/** 
	 * Returns the branchid.
	 * @return String
	 */
	public String getBranchid() {
		return branchid;
	}

	/** 
	 * Set the branchid.
	 * @param branchid The branchid to set
	 */
	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}
}