/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="marsTruckInfoForm"
 */
public class MarsTruckInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** trucknum property */
	private String trucknum;

	/** truckid property */
	private String truckid;

	/** truckphoto property */
	private String truckphoto;

	/** truckisvacancy property */
	private String truckisvacancy;

	/** truckenginenum property */
	private String truckenginenum;

	/** truckinsurancenum property */
	private String truckinsurancenum;

	/** truckrunnum property */
	private String truckrunnum;

	/** truckcolor property */
	private String truckcolor;

	/** tmid property */
	private String tmid;

	/** branchid property */
	private String branchid;

	/** truckbuydata property */
	private String truckbuydata;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the trucknum.
	 * @return String
	 */
	public String getTrucknum() {
		return trucknum;
	}

	/** 
	 * Set the trucknum.
	 * @param trucknum The trucknum to set
	 */
	public void setTrucknum(String trucknum) {
		this.trucknum = trucknum;
	}

	/** 
	 * Returns the truckid.
	 * @return String
	 */
	public String getTruckid() {
		return truckid;
	}

	/** 
	 * Set the truckid.
	 * @param truckid The truckid to set
	 */
	public void setTruckid(String truckid) {
		this.truckid = truckid;
	}

	/** 
	 * Returns the truckphoto.
	 * @return String
	 */
	public String getTruckphoto() {
		return truckphoto;
	}

	/** 
	 * Set the truckphoto.
	 * @param truckphoto The truckphoto to set
	 */
	public void setTruckphoto(String truckphoto) {
		this.truckphoto = truckphoto;
	}

	/** 
	 * Returns the truckisvacancy.
	 * @return String
	 */
	public String getTruckisvacancy() {
		return truckisvacancy;
	}

	/** 
	 * Set the truckisvacancy.
	 * @param truckisvacancy The truckisvacancy to set
	 */
	public void setTruckisvacancy(String truckisvacancy) {
		this.truckisvacancy = truckisvacancy;
	}

	/** 
	 * Returns the truckenginenum.
	 * @return String
	 */
	public String getTruckenginenum() {
		return truckenginenum;
	}

	/** 
	 * Set the truckenginenum.
	 * @param truckenginenum The truckenginenum to set
	 */
	public void setTruckenginenum(String truckenginenum) {
		this.truckenginenum = truckenginenum;
	}

	/** 
	 * Returns the truckinsurancenum.
	 * @return String
	 */
	public String getTruckinsurancenum() {
		return truckinsurancenum;
	}

	/** 
	 * Set the truckinsurancenum.
	 * @param truckinsurancenum The truckinsurancenum to set
	 */
	public void setTruckinsurancenum(String truckinsurancenum) {
		this.truckinsurancenum = truckinsurancenum;
	}

	/** 
	 * Returns the truckrunnum.
	 * @return String
	 */
	public String getTruckrunnum() {
		return truckrunnum;
	}

	/** 
	 * Set the truckrunnum.
	 * @param truckrunnum The truckrunnum to set
	 */
	public void setTruckrunnum(String truckrunnum) {
		this.truckrunnum = truckrunnum;
	}

	/** 
	 * Returns the truckcolor.
	 * @return String
	 */
	public String getTruckcolor() {
		return truckcolor;
	}

	/** 
	 * Set the truckcolor.
	 * @param truckcolor The truckcolor to set
	 */
	public void setTruckcolor(String truckcolor) {
		this.truckcolor = truckcolor;
	}

	/** 
	 * Returns the tmid.
	 * @return String
	 */
	public String getTmid() {
		return tmid;
	}

	/** 
	 * Set the tmid.
	 * @param tmid The tmid to set
	 */
	public void setTmid(String tmid) {
		this.tmid = tmid;
	}

	/** 
	 * Returns the branchid.
	 * @return String
	 */
	public String getBranchid() {
		return branchid;
	}

	/** 
	 * Set the branchid.
	 * @param branchid The branchid to set
	 */
	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}

	/** 
	 * Returns the truckbuydata.
	 * @return String
	 */
	public String getTruckbuydata() {
		return truckbuydata;
	}

	/** 
	 * Set the truckbuydata.
	 * @param truckbuydata The truckbuydata to set
	 */
	public void setTruckbuydata(String truckbuydata) {
		this.truckbuydata = truckbuydata;
	}
}