/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="marsCustomerInfoForm"
 */
public class MarsCustomerInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** customerphone property */
	private String customerphone;

	/** customeremail property */
	private String customeremail;

	/** customersex property */
	private String customersex;

	/** customerpostid property */
	private String customerpostid;

	/** customerfax property */
	private String customerfax;

	/** customerlinkman property */
	private String customerlinkman;

	/** branchid property */
	private String branchid;

	/** customerregdata property */
	private String customerregdata;

	/** customername property */
	private String customername;

	/** customerid property */
	private String customerid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the customerphone.
	 * @return String
	 */
	public String getCustomerphone() {
		return customerphone;
	}

	/** 
	 * Set the customerphone.
	 * @param customerphone The customerphone to set
	 */
	public void setCustomerphone(String customerphone) {
		this.customerphone = customerphone;
	}

	/** 
	 * Returns the customeremail.
	 * @return String
	 */
	public String getCustomeremail() {
		return customeremail;
	}

	/** 
	 * Set the customeremail.
	 * @param customeremail The customeremail to set
	 */
	public void setCustomeremail(String customeremail) {
		this.customeremail = customeremail;
	}

	/** 
	 * Returns the customersex.
	 * @return String
	 */
	public String getCustomersex() {
		return customersex;
	}

	/** 
	 * Set the customersex.
	 * @param customersex The customersex to set
	 */
	public void setCustomersex(String customersex) {
		this.customersex = customersex;
	}

	/** 
	 * Returns the customerpostid.
	 * @return String
	 */
	public String getCustomerpostid() {
		return customerpostid;
	}

	/** 
	 * Set the customerpostid.
	 * @param customerpostid The customerpostid to set
	 */
	public void setCustomerpostid(String customerpostid) {
		this.customerpostid = customerpostid;
	}

	/** 
	 * Returns the customerfax.
	 * @return String
	 */
	public String getCustomerfax() {
		return customerfax;
	}

	/** 
	 * Set the customerfax.
	 * @param customerfax The customerfax to set
	 */
	public void setCustomerfax(String customerfax) {
		this.customerfax = customerfax;
	}

	/** 
	 * Returns the customerlinkman.
	 * @return String
	 */
	public String getCustomerlinkman() {
		return customerlinkman;
	}

	/** 
	 * Set the customerlinkman.
	 * @param customerlinkman The customerlinkman to set
	 */
	public void setCustomerlinkman(String customerlinkman) {
		this.customerlinkman = customerlinkman;
	}

	/** 
	 * Returns the branchid.
	 * @return String
	 */
	public String getBranchid() {
		return branchid;
	}

	/** 
	 * Set the branchid.
	 * @param branchid The branchid to set
	 */
	public void setBranchid(String branchid) {
		this.branchid = branchid;
	}

	/** 
	 * Returns the customerregdata.
	 * @return String
	 */
	public String getCustomerregdata() {
		return customerregdata;
	}

	/** 
	 * Set the customerregdata.
	 * @param customerregdata The customerregdata to set
	 */
	public void setCustomerregdata(String customerregdata) {
		this.customerregdata = customerregdata;
	}

	/** 
	 * Returns the customername.
	 * @return String
	 */
	public String getCustomername() {
		return customername;
	}

	/** 
	 * Set the customername.
	 * @param customername The customername to set
	 */
	public void setCustomername(String customername) {
		this.customername = customername;
	}

	/** 
	 * Returns the customerid.
	 * @return String
	 */
	public String getCustomerid() {
		return customerid;
	}

	/** 
	 * Set the customerid.
	 * @param customerid The customerid to set
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}
}