/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="mosterTrafficLogForm"
 */
public class MosterTrafficLogForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchID property */
	private String branchID;

	/** branchName property */
	private String branchName;
	
	/** tLID property */
	private String tLID;

	/** trafficLogID property */
	private String trafficLogID;

	/** billID property */
	private String billID;

	
	/** truckNum property */
	private String truckNum;
	
	/** billstate property */
	private String billstate;
	
	/** billStateName property */
	private String billStateName;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchID.
	 * @return String
	 */
	public String getBranchID() {
		return branchID;
	}

	/** 
	 * Set the branchID.
	 * @param branchID The branchID to set
	 */
	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	/** 
	 * Returns the tLID.
	 * @return String
	 */
	public String getTLID() {
		return tLID;
	}

	/** 
	 * Set the tLID.
	 * @param tLID The tLID to set
	 */
	public void setTLID(String tLID) {
		this.tLID = tLID;
	}

	/** 
	 * Returns the trafficLogID.
	 * @return String
	 */
	public String getTrafficLogID() {
		return trafficLogID;
	}

	/** 
	 * Set the trafficLogID.
	 * @param trafficLogID The trafficLogID to set
	 */
	public void setTrafficLogID(String trafficLogID) {
		this.trafficLogID = trafficLogID;
	}

	/** 
	 * Returns the billID.
	 * @return String
	 */
	public String getBillID() {
		return billID;
	}

	/** 
	 * Set the billID.
	 * @param billID The billID to set
	 */
	public void setBillID(String billID) {
		this.billID = billID;
	}

	public String getTruckNum() {
		return truckNum;
	}

	public void setTruckNum(String truckNum) {
		this.truckNum = truckNum;
	}

	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getBillstate() {
		return billstate;
	}

	public void setBillstate(String billstate) {
		this.billstate = billstate;
	}

	public String getBillStateName() {
		return billStateName;
	}

	public void setBillStateName(String billStateName) {
		this.billStateName = billStateName;
	}
}