/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="mosterCargoVectorForm"
 */
public class MosterCargoVectorForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cargoID property */
	private String cargoID;

	/** cvID property */
	private String cvID;

	/** billID property */
	private String billID;

	/** cargoName property */
	private String cargoName;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cargoID.
	 * @return String
	 */
	public String getCargoID() {
		return cargoID;
	}

	/** 
	 * Set the cargoID.
	 * @param cargoID The cargoID to set
	 */
	public void setCargoID(String cargoID) {
		this.cargoID = cargoID;
	}

	/** 
	 * Returns the cvID.
	 * @return String
	 */
	public String getCvID() {
		return cvID;
	}

	/** 
	 * Set the cvID.
	 * @param cvID The cvID to set
	 */
	public void setCvID(String cvID) {
		this.cvID = cvID;
	}

	/** 
	 * Returns the billID.
	 * @return String
	 */
	public String getBillID() {
		return billID;
	}

	/** 
	 * Set the billID.
	 * @param billID The billID to set
	 */
	public void setBillID(String billID) {
		this.billID = billID;
	}

	public String getCargoName() {
		return cargoName;
	}

	public void setCargoName(String cargoName) {
		this.cargoName = cargoName;
	}
}