/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="mosterCargoInfoForm"
 */
public class MosterCargoInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cargoUnit property */
	private String cargoUnit;

	/** cargoFreight property */
	private String cargoFreight;

	/** branchName property */
	private String branchName;

	/** cargoAmends property */
	private String cargoAmends;

	/** cargoStartData property */
	private String cargoStartData;

	/** cargoEndData property */
	private String cargoEndData;

	/** cargoBulk property */
	private String cargoBulk;

	/** cargoName property */
	private String cargoName;

	/** cargoMemo property */
	private String cargoMemo;

	/** cargoState property */
	private String cargoState;

	/** branchID property */
	private String branchID;

	/** cargoID property */
	private String cargoID;

	/** cargoNum property */
	private String cargoNum;

	/** cargoWeight property */
	private String cargoWeight;

	/** cargoValue property */
	private String cargoValue;


	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cargoUnit.
	 * @return String
	 */
	public String getCargoUnit() {
		return cargoUnit;
	}

	/** 
	 * Set the cargoUnit.
	 * @param cargoUnit The cargoUnit to set
	 */
	public void setCargoUnit(String cargoUnit) {
		this.cargoUnit = cargoUnit;
	}

	/** 
	 * Returns the cargoFreight.
	 * @return String
	 */
	public String getCargoFreight() {
		return cargoFreight;
	}

	/** 
	 * Set the cargoFreight.
	 * @param cargoFreight The cargoFreight to set
	 */
	public void setCargoFreight(String cargoFreight) {
		this.cargoFreight = cargoFreight;
	}

	/** 
	 * Returns the branchName.
	 * @return String
	 */
	public String getBranchName() {
		return branchName;
	}

	/** 
	 * Set the branchName.
	 * @param branchName The branchName to set
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	/** 
	 * Returns the cargoAmends.
	 * @return String
	 */
	public String getCargoAmends() {
		return cargoAmends;
	}

	/** 
	 * Set the cargoAmends.
	 * @param cargoAmends The cargoAmends to set
	 */
	public void setCargoAmends(String cargoAmends) {
		this.cargoAmends = cargoAmends;
	}

	/** 
	 * Returns the cargoStartData.
	 * @return String
	 */
	public String getCargoStartData() {
		return cargoStartData;
	}

	/** 
	 * Set the cargoStartData.
	 * @param cargoStartData The cargoStartData to set
	 */
	public void setCargoStartData(String cargoStartData) {
		this.cargoStartData = cargoStartData;
	}

	/** 
	 * Returns the cargoEndData.
	 * @return String
	 */
	public String getCargoEndData() {
		return cargoEndData;
	}

	/** 
	 * Set the cargoEndData.
	 * @param cargoEndData The cargoEndData to set
	 */
	public void setCargoEndData(String cargoEndData) {
		this.cargoEndData = cargoEndData;
	}

	/** 
	 * Returns the cargoBulk.
	 * @return String
	 */
	public String getCargoBulk() {
		return cargoBulk;
	}

	/** 
	 * Set the cargoBulk.
	 * @param cargoBulk The cargoBulk to set
	 */
	public void setCargoBulk(String cargoBulk) {
		this.cargoBulk = cargoBulk;
	}

	/** 
	 * Returns the cargoName.
	 * @return String
	 */
	public String getCargoName() {
		return cargoName;
	}

	/** 
	 * Set the cargoName.
	 * @param cargoName The cargoName to set
	 */
	public void setCargoName(String cargoName) {
		this.cargoName = cargoName;
	}

	/** 
	 * Returns the cargoMemo.
	 * @return String
	 */
	public String getCargoMemo() {
		return cargoMemo;
	}

	/** 
	 * Set the cargoMemo.
	 * @param cargoMemo The cargoMemo to set
	 */
	public void setCargoMemo(String cargoMemo) {
		this.cargoMemo = cargoMemo;
	}

	/** 
	 * Returns the cargoState.
	 * @return String
	 */
	public String getCargoState() {
		return cargoState;
	}

	/** 
	 * Set the cargoState.
	 * @param cargoState The cargoState to set
	 */
	public void setCargoState(String cargoState) {
		this.cargoState = cargoState;
	}

	/** 
	 * Returns the branchID.
	 * @return String
	 */
	public String getBranchID() {
		return branchID;
	}

	/** 
	 * Set the branchID.
	 * @param branchID The branchID to set
	 */
	public void setBranchID(String branchID) {
		this.branchID = branchID;
	}

	/** 
	 * Returns the cargoID.
	 * @return String
	 */
	public String getCargoID() {
		return cargoID;
	}

	/** 
	 * Set the cargoID.
	 * @param cargoID The cargoID to set
	 */
	public void setCargoID(String cargoID) {
		this.cargoID = cargoID;
	}

	/** 
	 * Returns the cargoNum.
	 * @return String
	 */
	public String getCargoNum() {
		return cargoNum;
	}

	/** 
	 * Set the cargoNum.
	 * @param cargoNum The cargoNum to set
	 */
	public void setCargoNum(String cargoNum) {
		this.cargoNum = cargoNum;
	}

	/** 
	 * Returns the cargoWeight.
	 * @return String
	 */
	public String getCargoWeight() {
		return cargoWeight;
	}

	/** 
	 * Set the cargoWeight.
	 * @param cargoWeight The cargoWeight to set
	 */
	public void setCargoWeight(String cargoWeight) {
		this.cargoWeight = cargoWeight;
	}

	/** 
	 * Returns the cargoValue.
	 * @return String
	 */
	public String getCargoValue() {
		return cargoValue;
	}

	/** 
	 * Set the cargoValue.
	 * @param cargoValue The cargoValue to set
	 */
	public void setCargoValue(String cargoValue) {
		this.cargoValue = cargoValue;
	}

}