/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import java.util.Vector;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="mosterBillInfoForm"
 */
public class MosterBillInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userName property */
	private String userName;

	/** userID property */
	private String userID;

	/** billData property */
	private String billData;

	/** truckLine property */
	private String truckLine;


	/** billMemo property */
	private String billMemo;

	/** sendBranchID property */
	private String sendBranchID;

	/** receiveBranchID property */
	private String receiveBranchID;

	/** billStateName property */
	private String billStateName;

	/** billStateID property */
	private String billStateID;

	/** sendBranchName property */
	private String sendBranchName;


	/** receiveBranchName property */
	private String receiveBranchName;

	/** receiveName property */
	private String receiveName;

	/** receiveID property */
	private String receiveID;

	/** payerName property */
	private String payerName;

	/** sendID property */
	private String sendID;

	/** sendName property */
	private String sendName;

	/** billID property */
	private String billID;

	/** cargoValue property */
	private String[] cargoIDs;
	
	/** cargoValue property */
	private Vector cargos;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the userID.
	 * @return String
	 */
	public String getUserID() {
		return userID;
	}

	/** 
	 * Set the userID.
	 * @param userID The userID to set
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/** 
	 * Returns the billData.
	 * @return String
	 */
	public String getBillData() {
		return billData;
	}

	/** 
	 * Set the billData.
	 * @param billData The billData to set
	 */
	public void setBillData(String billData) {
		this.billData = billData;
	}

	/** 
	 * Returns the truckLine.
	 * @return String
	 */
	public String getTruckLine() {
		return truckLine;
	}

	/** 
	 * Set the truckLine.
	 * @param truckLine The truckLine to set
	 */
	public void setTruckLine(String truckLine) {
		this.truckLine = truckLine;
	}


	/** 
	 * Returns the billMemo.
	 * @return String
	 */
	public String getBillMemo() {
		return billMemo;
	}

	/** 
	 * Set the billMemo.
	 * @param billMemo The billMemo to set
	 */
	public void setBillMemo(String billMemo) {
		this.billMemo = billMemo;
	}

	/** 
	 * Returns the sendBranchID.
	 * @return String
	 */
	public String getSendBranchID() {
		return sendBranchID;
	}

	/** 
	 * Set the sendBranchID.
	 * @param sendBranchID The sendBranchID to set
	 */
	public void setSendBranchID(String sendBranchID) {
		this.sendBranchID = sendBranchID;
	}

	/** 
	 * Returns the receiveBranchID.
	 * @return String
	 */
	public String getReceiveBranchID() {
		return receiveBranchID;
	}

	/** 
	 * Set the receiveBranchID.
	 * @param receiveBranchID The receiveBranchID to set
	 */
	public void setReceiveBranchID(String receiveBranchID) {
		this.receiveBranchID = receiveBranchID;
	}

	/** 
	 * Returns the billStateName.
	 * @return String
	 */
	public String getBillStateName() {
		return billStateName;
	}

	/** 
	 * Set the billStateName.
	 * @param billStateName The billStateName to set
	 */
	public void setBillStateName(String billStateName) {
		this.billStateName = billStateName;
	}

	/** 
	 * Returns the billStateID.
	 * @return String
	 */
	public String getBillStateID() {
		return billStateID;
	}

	/** 
	 * Set the billStateID.
	 * @param billStateID The billStateID to set
	 */
	public void setBillStateID(String billStateID) {
		this.billStateID = billStateID;
	}

	/** 
	 * Returns the sendBranchName.
	 * @return String
	 */
	public String getSendBranchName() {
		return sendBranchName;
	}

	/** 
	 * Set the sendBranchName.
	 * @param sendBranchName The sendBranchName to set
	 */
	public void setSendBranchName(String sendBranchName) {
		this.sendBranchName = sendBranchName;
	}


	/** 
	 * Returns the receiveBranchName.
	 * @return String
	 */
	public String getReceiveBranchName() {
		return receiveBranchName;
	}

	/** 
	 * Set the receiveBranchName.
	 * @param receiveBranchName The receiveBranchName to set
	 */
	public void setReceiveBranchName(String receiveBranchName) {
		this.receiveBranchName = receiveBranchName;
	}

	/** 
	 * Returns the receiveName.
	 * @return String
	 */
	public String getReceiveName() {
		return receiveName;
	}

	/** 
	 * Set the receiveName.
	 * @param receiveName The receiveName to set
	 */
	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	/** 
	 * Returns the receiveID.
	 * @return String
	 */
	public String getReceiveID() {
		return receiveID;
	}

	/** 
	 * Set the receiveID.
	 * @param receiveID The receiveID to set
	 */
	public void setReceiveID(String receiveID) {
		this.receiveID = receiveID;
	}

	/** 
	 * Returns the payerName.
	 * @return String
	 */
	public String getPayerName() {
		return payerName;
	}

	/** 
	 * Set the payerName.
	 * @param payerName The payerName to set
	 */
	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	/** 
	 * Returns the sendID.
	 * @return String
	 */
	public String getSendID() {
		return sendID;
	}

	/** 
	 * Set the sendID.
	 * @param sendID The sendID to set
	 */
	public void setSendID(String sendID) {
		this.sendID = sendID;
	}

	/** 
	 * Returns the sendName.
	 * @return String
	 */
	public String getSendName() {
		return sendName;
	}

	/** 
	 * Set the sendName.
	 * @param sendName The sendName to set
	 */
	public void setSendName(String sendName) {
		this.sendName = sendName;
	}

	/** 
	 * Returns the billID.
	 * @return String
	 */
	public String getBillID() {
		return billID;
	}

	/** 
	 * Set the billID.
	 * @param billID The billID to set
	 */
	public void setBillID(String billID) {
		this.billID = billID;
	}

	public String[] getCargoIDs() {
		return cargoIDs;
	}

	public void setCargoIDs(String[] cargoIDs) {
		this.cargoIDs = cargoIDs;
	}

	public Vector getCargos() {
		return cargos;
	}

	public void setCargos(Vector cargos) {
		this.cargos = cargos;
	}
}