/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import java.util.Vector;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2007
 * 
 * XDoclet definition:
 * @struts.form name="optBillInfoForm"
 */
public class OptBillInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** receivebranchname property */
	private String receivebranchname;

	/** billid property */
	private String billid;

	/** sendbranchname property */
	private String sendbranchname;

	/** cargoids property */
	private String[] cargoids;

	/** billdata property */
	private String billdata;

	/** sendbranchid property */
	private String sendbranchid;

	/** cargos property */
	private Vector cargos;

	/** sendid property */
	private String sendid;

	/** truckline property */
	private String truckline;

	/** payername property */
	private String payername;

	/** userid property */
	private String userid;

	/** billmemo property */
	private String billmemo;

	/** sendname property */
	private String sendname;

	/** receiveid property */
	private String receiveid;

	/** billstateid property */
	private String billstateid;

	/** username property */
	private String username;

	/** receivebranchid property */
	private String receivebranchid;

	/** receivename property */
	private String receivename;

	/** billstatename property */
	private String billstatename;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the receivebranchname.
	 * @return String
	 */
	public String getReceivebranchname() {
		return receivebranchname;
	}

	/** 
	 * Set the receivebranchname.
	 * @param receivebranchname The receivebranchname to set
	 */
	public void setReceivebranchname(String receivebranchname) {
		this.receivebranchname = receivebranchname;
	}

	/** 
	 * Returns the billid.
	 * @return String
	 */
	public String getBillid() {
		return billid;
	}

	/** 
	 * Set the billid.
	 * @param billid The billid to set
	 */
	public void setBillid(String billid) {
		this.billid = billid;
	}

	/** 
	 * Returns the sendbranchname.
	 * @return String
	 */
	public String getSendbranchname() {
		return sendbranchname;
	}

	/** 
	 * Set the sendbranchname.
	 * @param sendbranchname The sendbranchname to set
	 */
	public void setSendbranchname(String sendbranchname) {
		this.sendbranchname = sendbranchname;
	}

	/** 
	 * Returns the cargoids.
	 * @return String[]
	 */
	public String[] getCargoids() {
		return cargoids;
	}

	/** 
	 * Set the cargoids.
	 * @param cargoids The cargoids to set
	 */
	public void setCargoids(String[] cargoids) {
		this.cargoids = cargoids;
	}

	/** 
	 * Returns the billdata.
	 * @return String
	 */
	public String getBilldata() {
		return billdata;
	}

	/** 
	 * Set the billdata.
	 * @param billdata The billdata to set
	 */
	public void setBilldata(String billdata) {
		this.billdata = billdata;
	}

	/** 
	 * Returns the sendbranchid.
	 * @return String
	 */
	public String getSendbranchid() {
		return sendbranchid;
	}

	/** 
	 * Set the sendbranchid.
	 * @param sendbranchid The sendbranchid to set
	 */
	public void setSendbranchid(String sendbranchid) {
		this.sendbranchid = sendbranchid;
	}

	/** 
	 * Returns the cargos.
	 * @return Vector
	 */
	public Vector getCargos() {
		return cargos;
	}

	/** 
	 * Set the cargos.
	 * @param cargos The cargos to set
	 */
	public void setCargos(Vector cargos) {
		this.cargos = cargos;
	}

	/** 
	 * Returns the sendid.
	 * @return String
	 */
	public String getSendid() {
		return sendid;
	}

	/** 
	 * Set the sendid.
	 * @param sendid The sendid to set
	 */
	public void setSendid(String sendid) {
		this.sendid = sendid;
	}

	/** 
	 * Returns the truckline.
	 * @return String
	 */
	public String getTruckline() {
		return truckline;
	}

	/** 
	 * Set the truckline.
	 * @param truckline The truckline to set
	 */
	public void setTruckline(String truckline) {
		this.truckline = truckline;
	}

	/** 
	 * Returns the payername.
	 * @return String
	 */
	public String getPayername() {
		return payername;
	}

	/** 
	 * Set the payername.
	 * @param payername The payername to set
	 */
	public void setPayername(String payername) {
		this.payername = payername;
	}

	/** 
	 * Returns the userid.
	 * @return String
	 */
	public String getUserid() {
		return userid;
	}

	/** 
	 * Set the userid.
	 * @param userid The userid to set
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/** 
	 * Returns the billmemo.
	 * @return String
	 */
	public String getBillmemo() {
		return billmemo;
	}

	/** 
	 * Set the billmemo.
	 * @param billmemo The billmemo to set
	 */
	public void setBillmemo(String billmemo) {
		this.billmemo = billmemo;
	}

	/** 
	 * Returns the sendname.
	 * @return String
	 */
	public String getSendname() {
		return sendname;
	}

	/** 
	 * Set the sendname.
	 * @param sendname The sendname to set
	 */
	public void setSendname(String sendname) {
		this.sendname = sendname;
	}

	/** 
	 * Returns the receiveid.
	 * @return String
	 */
	public String getReceiveid() {
		return receiveid;
	}

	/** 
	 * Set the receiveid.
	 * @param receiveid The receiveid to set
	 */
	public void setReceiveid(String receiveid) {
		this.receiveid = receiveid;
	}

	/** 
	 * Returns the billstateid.
	 * @return String
	 */
	public String getBillstateid() {
		return billstateid;
	}

	/** 
	 * Set the billstateid.
	 * @param billstateid The billstateid to set
	 */
	public void setBillstateid(String billstateid) {
		this.billstateid = billstateid;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the receivebranchid.
	 * @return String
	 */
	public String getReceivebranchid() {
		return receivebranchid;
	}

	/** 
	 * Set the receivebranchid.
	 * @param receivebranchid The receivebranchid to set
	 */
	public void setReceivebranchid(String receivebranchid) {
		this.receivebranchid = receivebranchid;
	}

	/** 
	 * Returns the receivename.
	 * @return String
	 */
	public String getReceivename() {
		return receivename;
	}

	/** 
	 * Set the receivename.
	 * @param receivename The receivename to set
	 */
	public void setReceivename(String receivename) {
		this.receivename = receivename;
	}

	/** 
	 * Returns the billstatename.
	 * @return String
	 */
	public String getBillstatename() {
		return billstatename;
	}

	/** 
	 * Set the billstatename.
	 * @param billstatename The billstatename to set
	 */
	public void setBillstatename(String billstatename) {
		this.billstatename = billstatename;
	}
}