/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2007
 * 
 * XDoclet definition:
 * @struts.form name="optOperationForm"
 */
public class OptOperationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** opname property */
	private String opname;

	/** opfid property */
	private String opfid;

	/** opurl property */
	private String opurl;

	/** opid property */
	private String opid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the opname.
	 * @return String
	 */
	public String getOpname() {
		return opname;
	}

	/** 
	 * Set the opname.
	 * @param opname The opname to set
	 */
	public void setOpname(String opname) {
		this.opname = opname;
	}

	/** 
	 * Returns the opfid.
	 * @return String
	 */
	public String getOpfid() {
		return opfid;
	}

	/** 
	 * Set the opfid.
	 * @param opfid The opfid to set
	 */
	public void setOpfid(String opfid) {
		this.opfid = opfid;
	}

	/** 
	 * Returns the opurl.
	 * @return String
	 */
	public String getOpurl() {
		return opurl;
	}

	/** 
	 * Set the opurl.
	 * @param opurl The opurl to set
	 */
	public void setOpurl(String opurl) {
		this.opurl = opurl;
	}

	/** 
	 * Returns the opid.
	 * @return String
	 */
	public String getOpid() {
		return opid;
	}

	/** 
	 * Set the opid.
	 * @param opid The opid to set
	 */
	public void setOpid(String opid) {
		this.opid = opid;
	}
}