/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2007
 * 
 * XDoclet definition:
 * @struts.form name="optRoleInfoForm"
 */
public class OptRoleInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** roleclient property */
	private String roleclient;

	/** roletraffic property */
	private String roletraffic;

	/** rolename property */
	private String rolename;

	/** rolebasicinfo property */
	private String rolebasicinfo;

	/** rolequery property */
	private String rolequery;

	/** rolebranch property */
	private String rolebranch;

	/** roleticket property */
	private String roleticket;

	/** roleid property */
	private String roleid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the roleclient.
	 * @return String
	 */
	public String getRoleclient() {
		return roleclient;
	}

	/** 
	 * Set the roleclient.
	 * @param roleclient The roleclient to set
	 */
	public void setRoleclient(String roleclient) {
		this.roleclient = roleclient;
	}

	/** 
	 * Returns the roletraffic.
	 * @return String
	 */
	public String getRoletraffic() {
		return roletraffic;
	}

	/** 
	 * Set the roletraffic.
	 * @param roletraffic The roletraffic to set
	 */
	public void setRoletraffic(String roletraffic) {
		this.roletraffic = roletraffic;
	}

	/** 
	 * Returns the rolename.
	 * @return String
	 */
	public String getRolename() {
		return rolename;
	}

	/** 
	 * Set the rolename.
	 * @param rolename The rolename to set
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	/** 
	 * Returns the rolebasicinfo.
	 * @return String
	 */
	public String getRolebasicinfo() {
		return rolebasicinfo;
	}

	/** 
	 * Set the rolebasicinfo.
	 * @param rolebasicinfo The rolebasicinfo to set
	 */
	public void setRolebasicinfo(String rolebasicinfo) {
		this.rolebasicinfo = rolebasicinfo;
	}

	/** 
	 * Returns the rolequery.
	 * @return String
	 */
	public String getRolequery() {
		return rolequery;
	}

	/** 
	 * Set the rolequery.
	 * @param rolequery The rolequery to set
	 */
	public void setRolequery(String rolequery) {
		this.rolequery = rolequery;
	}

	/** 
	 * Returns the rolebranch.
	 * @return String
	 */
	public String getRolebranch() {
		return rolebranch;
	}

	/** 
	 * Set the rolebranch.
	 * @param rolebranch The rolebranch to set
	 */
	public void setRolebranch(String rolebranch) {
		this.rolebranch = rolebranch;
	}

	/** 
	 * Returns the roleticket.
	 * @return String
	 */
	public String getRoleticket() {
		return roleticket;
	}

	/** 
	 * Set the roleticket.
	 * @param roleticket The roleticket to set
	 */
	public void setRoleticket(String roleticket) {
		this.roleticket = roleticket;
	}

	/** 
	 * Returns the roleid.
	 * @return String
	 */
	public String getRoleid() {
		return roleid;
	}

	/** 
	 * Set the roleid.
	 * @param roleid The roleid to set
	 */
	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}
}