/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="yasak_BillInfoForm"
 */
public class Yasak_BillInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** sendBranchName property */
	private String sendBranchName;

	/** userName property */
	private String userName;

	/** billId property */
	private String billId;

	/** billDataName property */
	private String billDataName;

	/** billData property */
	private String billData;

	/** receiveName property */
	private String receiveName;

	/** userId property */
	private String userId;

	/** billDataId property */
	private String billDataId;

	/** receiveId property */
	private String receiveId;

	/** sendId property */
	private String sendId;

	/** sendBranchId property */
	private String sendBranchId;

	/** sendName property */
	private String sendName;
	
	private String receiveBranchId;
	
	private String receiveBranchName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sendBranchName.
	 * @return String
	 */
	public String getSendBranchName() {
		return sendBranchName;
	}

	/** 
	 * Set the sendBranchName.
	 * @param sendBranchName The sendBranchName to set
	 */
	public void setSendBranchName(String sendBranchName) {
		this.sendBranchName = sendBranchName;
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the billId.
	 * @return String
	 */
	public String getBillId() {
		return billId;
	}

	/** 
	 * Set the billId.
	 * @param billId The billId to set
	 */
	public void setBillId(String billId) {
		this.billId = billId;
	}

	/** 
	 * Returns the billDataName.
	 * @return String
	 */
	public String getBillDataName() {
		return billDataName;
	}

	/** 
	 * Set the billDataName.
	 * @param billDataName The billDataName to set
	 */
	public void setBillDataName(String billDataName) {
		this.billDataName = billDataName;
	}

	/** 
	 * Returns the billData.
	 * @return String
	 */
	public String getBillData() {
		return billData;
	}

	/** 
	 * Set the billData.
	 * @param billData The billData to set
	 */
	public void setBillData(String billData) {
		this.billData = billData;
	}

	/** 
	 * Returns the receiveName.
	 * @return String
	 */
	public String getReceiveName() {
		return receiveName;
	}

	/** 
	 * Set the receiveName.
	 * @param receiveName The receiveName to set
	 */
	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	/** 
	 * Returns the userId.
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the billDataId.
	 * @return String
	 */
	public String getBillDataId() {
		return billDataId;
	}

	/** 
	 * Set the billDataId.
	 * @param billDataId The billDataId to set
	 */
	public void setBillDataId(String billDataId) {
		this.billDataId = billDataId;
	}

	/** 
	 * Returns the receiveId.
	 * @return String
	 */
	public String getReceiveId() {
		return receiveId;
	}

	/** 
	 * Set the receiveId.
	 * @param receiveId The receiveId to set
	 */
	public void setReceiveId(String receiveId) {
		this.receiveId = receiveId;
	}

	/** 
	 * Returns the sendId.
	 * @return String
	 */
	public String getSendId() {
		return sendId;
	}

	/** 
	 * Set the sendId.
	 * @param sendId The sendId to set
	 */
	public void setSendId(String sendId) {
		this.sendId = sendId;
	}

	/** 
	 * Returns the sendBranchId.
	 * @return String
	 */
	public String getSendBranchId() {
		return sendBranchId;
	}

	/** 
	 * Set the sendBranchId.
	 * @param sendBranchId The sendBranchId to set
	 */
	public void setSendBranchId(String sendBranchId) {
		this.sendBranchId = sendBranchId;
	}

	/** 
	 * Returns the sendName.
	 * @return String
	 */
	public String getSendName() {
		return sendName;
	}

	/** 
	 * Set the sendName.
	 * @param sendName The sendName to set
	 */
	public void setSendName(String sendName) {
		this.sendName = sendName;
	}

	public String getReceiveBranchId() {
		return receiveBranchId;
	}

	public void setReceiveBranchId(String receiveBranchId) {
		this.receiveBranchId = receiveBranchId;
	}

	public String getReceiveBranchName() {
		return receiveBranchName;
	}

	public void setReceiveBranchName(String receiveBranchName) {
		this.receiveBranchName = receiveBranchName;
	}
}