/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="yasak_CustomerForm"
 */
public class Yasak_CustomerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** customerPhone property */
	private String customerPhone;

	/** branchId property */
	private String branchId;

	/** customerlinkMan property */
	private String customerLinkMan;

	/** branchName property */
	private String branchName;

	/** customerRegData property */
	private String customerRegData;

	/** customerSex property */
	private String customerSex;

	/** customerName property */
	private String customerName;

	/** customerEmail property */
	private String customerEmail;

	/** customerFax property */
	private String customerFax;

	/** customerPostId property */
	private String customerPostId;

	/** customerId property */
	private String customerId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the customerPhone.
	 * @return String
	 */
	public String getCustomerPhone() {
		return customerPhone;
	}

	/** 
	 * Set the customerPhone.
	 * @param customerPhone The customerPhone to set
	 */
	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	/** 
	 * Returns the branchId.
	 * @return String
	 */
	public String getBranchId() {
		return branchId;
	}

	/** 
	 * Set the branchId.
	 * @param branchId The branchId to set
	 */
	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	/** 
	 * Returns the branchName.
	 * @return String
	 */
	public String getBranchName() {
		return branchName;
	}

	/** 
	 * Set the branchName.
	 * @param branchName The branchName to set
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	/** 
	 * Returns the customerRegData.
	 * @return String
	 */
	public String getCustomerRegData() {
		return customerRegData;
	}

	/** 
	 * Set the customerRegData.
	 * @param customerRegData The customerRegData to set
	 */
	public void setCustomerRegData(String customerRegData) {
		this.customerRegData = customerRegData;
	}

	/** 
	 * Returns the customerSex.
	 * @return String
	 */
	public String getCustomerSex() {
		return customerSex;
	}

	/** 
	 * Set the customerSex.
	 * @param customerSex The customerSex to set
	 */
	public void setCustomerSex(String customerSex) {
		this.customerSex = customerSex;
	}

	/** 
	 * Returns the customerName.
	 * @return String
	 */
	public String getCustomerName() {
		return customerName;
	}

	/** 
	 * Set the customerName.
	 * @param customerName The customerName to set
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/** 
	 * Returns the customerEmail.
	 * @return String
	 */
	public String getCustomerEmail() {
		return customerEmail;
	}

	/** 
	 * Set the customerEmail.
	 * @param customerEmail The customerEmail to set
	 */
	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	/** 
	 * Returns the customerFax.
	 * @return String
	 */
	public String getCustomerFax() {
		return customerFax;
	}

	/** 
	 * Set the customerFax.
	 * @param customerFax The customerFax to set
	 */
	public void setCustomerFax(String customerFax) {
		this.customerFax = customerFax;
	}

	/** 
	 * Returns the customerPostId.
	 * @return String
	 */
	public String getCustomerPostId() {
		return customerPostId;
	}

	/** 
	 * Set the customerPostId.
	 * @param customerPostId The customerPostId to set
	 */
	public void setCustomerPostId(String customerPostId) {
		this.customerPostId = customerPostId;
	}

	/** 
	 * Returns the customerId.
	 * @return String
	 */
	public String getCustomerId() {
		return customerId;
	}

	/** 
	 * Set the customerId.
	 * @param customerId The customerId to set
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getCustomerLinkMan() {
		return customerLinkMan;
	}

	public void setCustomerLinkMan(String customerLinkMan) {
		this.customerLinkMan = customerLinkMan;
	}
}