/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="yasak_BranchInfoForm"
 */
public class Yasak_BranchInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchId property */
	private String branchId;

	/** branchName property */
	private String branchName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchId.
	 * @return String
	 */
	public String getBranchId() {
		return branchId;
	}

	/** 
	 * Set the branchId.
	 * @param branchId The branchId to set
	 */
	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	/** 
	 * Returns the branchName.
	 * @return String
	 */
	public String getBranchName() {
		return branchName;
	}

	/** 
	 * Set the branchName.
	 * @param branchName The branchName to set
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}
}