/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2007
 * 
 * XDoclet definition:
 * @struts.form name="yasak_BillInfoAllForm"
 */
public class Yasak_BillInfoAllForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userName property */
	private String userName;

	/** billData property */
	private String billData;

	/** receiveBranchId property */
	private String receiveBranchId;

	/** userId property */
	private String userId;

	/** truckLine property */
	private String truckLine;

	/** billMemo property */
	private String billMemo;

	/** billStateName property */
	private String billStateName;

	/** sendBranchName property */
	private String sendBranchName;

	/** billId property */
	private String billId;

	/** billStateId property */
	private String billStateId;

	/** receiveBranchName property */
	private String receiveBranchName;

	/** receiveName property */
	private String receiveName;

	/** receiveId property */
	private String receiveId;

	/** payerName property */
	private String payerName;

	/** sendId property */
	private String sendId;

	/** sendBranchId property */
	private String sendBranchId;

	/** sendName property */
	private String sendName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the billData.
	 * @return String
	 */
	public String getBillData() {
		return billData;
	}

	/** 
	 * Set the billData.
	 * @param billData The billData to set
	 */
	public void setBillData(String billData) {
		this.billData = billData;
	}

	/** 
	 * Returns the receiveBranchId.
	 * @return String
	 */
	public String getReceiveBranchId() {
		return receiveBranchId;
	}

	/** 
	 * Set the receiveBranchId.
	 * @param receiveBranchId The receiveBranchId to set
	 */
	public void setReceiveBranchId(String receiveBranchId) {
		this.receiveBranchId = receiveBranchId;
	}

	/** 
	 * Returns the userId.
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the truckLine.
	 * @return String
	 */
	public String getTruckLine() {
		return truckLine;
	}

	/** 
	 * Set the truckLine.
	 * @param truckLine The truckLine to set
	 */
	public void setTruckLine(String truckLine) {
		this.truckLine = truckLine;
	}

	/** 
	 * Returns the billMemo.
	 * @return String
	 */
	public String getBillMemo() {
		return billMemo;
	}

	/** 
	 * Set the billMemo.
	 * @param billMemo The billMemo to set
	 */
	public void setBillMemo(String billMemo) {
		this.billMemo = billMemo;
	}

	/** 
	 * Returns the billStateName.
	 * @return String
	 */
	public String getBillStateName() {
		return billStateName;
	}

	/** 
	 * Set the billStateName.
	 * @param billStateName The billStateName to set
	 */
	public void setBillStateName(String billStateName) {
		this.billStateName = billStateName;
	}

	/** 
	 * Returns the sendBranchName.
	 * @return String
	 */
	public String getSendBranchName() {
		return sendBranchName;
	}

	/** 
	 * Set the sendBranchName.
	 * @param sendBranchName The sendBranchName to set
	 */
	public void setSendBranchName(String sendBranchName) {
		this.sendBranchName = sendBranchName;
	}

	/** 
	 * Returns the billId.
	 * @return String
	 */
	public String getBillId() {
		return billId;
	}

	/** 
	 * Set the billId.
	 * @param billId The billId to set
	 */
	public void setBillId(String billId) {
		this.billId = billId;
	}

	/** 
	 * Returns the billStateId.
	 * @return String
	 */
	public String getBillStateId() {
		return billStateId;
	}

	/** 
	 * Set the billStateId.
	 * @param billStateId The billStateId to set
	 */
	public void setBillStateId(String billStateId) {
		this.billStateId = billStateId;
	}

	/** 
	 * Returns the receiveBranchName.
	 * @return String
	 */
	public String getReceiveBranchName() {
		return receiveBranchName;
	}

	/** 
	 * Set the receiveBranchName.
	 * @param receiveBranchName The receiveBranchName to set
	 */
	public void setReceiveBranchName(String receiveBranchName) {
		this.receiveBranchName = receiveBranchName;
	}

	/** 
	 * Returns the receiveName.
	 * @return String
	 */
	public String getReceiveName() {
		return receiveName;
	}

	/** 
	 * Set the receiveName.
	 * @param receiveName The receiveName to set
	 */
	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	/** 
	 * Returns the receiveId.
	 * @return String
	 */
	public String getReceiveId() {
		return receiveId;
	}

	/** 
	 * Set the receiveId.
	 * @param receiveId The receiveId to set
	 */
	public void setReceiveId(String receiveId) {
		this.receiveId = receiveId;
	}

	/** 
	 * Returns the payerName.
	 * @return String
	 */
	public String getPayerName() {
		return payerName;
	}

	/** 
	 * Set the payerName.
	 * @param payerName The payerName to set
	 */
	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	/** 
	 * Returns the sendId.
	 * @return String
	 */
	public String getSendId() {
		return sendId;
	}

	/** 
	 * Set the sendId.
	 * @param sendId The sendId to set
	 */
	public void setSendId(String sendId) {
		this.sendId = sendId;
	}

	/** 
	 * Returns the sendBranchId.
	 * @return String
	 */
	public String getSendBranchId() {
		return sendBranchId;
	}

	/** 
	 * Set the sendBranchId.
	 * @param sendBranchId The sendBranchId to set
	 */
	public void setSendBranchId(String sendBranchId) {
		this.sendBranchId = sendBranchId;
	}

	/** 
	 * Returns the sendName.
	 * @return String
	 */
	public String getSendName() {
		return sendName;
	}

	/** 
	 * Set the sendName.
	 * @param sendName The sendName to set
	 */
	public void setSendName(String sendName) {
		this.sendName = sendName;
	}
}