/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-24-2008
 * 
 * XDoclet definition:
 * @struts.form name="yasak_AfficheInfoForm"
 */
public class Yasak_AfficheInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchId property */
	private String branchId;

	/** userName property */
	private String userName;

	/** afficheId property */
	private String afficheId;

	/** branchName property */
	private String branchName;

	/** userId property */
	private String userId;

	/** afficheData property */
	private String afficheData;

	/** afficheTitle property */
	private String afficheTitle;
	
	private String afficheContent;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchId.
	 * @return String
	 */
	public String getBranchId() {
		return branchId;
	}

	/** 
	 * Set the branchId.
	 * @param branchId The branchId to set
	 */
	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the afficheId.
	 * @return String
	 */
	public String getAfficheId() {
		return afficheId;
	}

	/** 
	 * Set the afficheId.
	 * @param afficheId The afficheId to set
	 */
	public void setAfficheId(String afficheId) {
		this.afficheId = afficheId;
	}

	/** 
	 * Returns the branchName.
	 * @return String
	 */
	public String getBranchName() {
		return branchName;
	}

	/** 
	 * Set the branchName.
	 * @param branchName The branchName to set
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	/** 
	 * Returns the userId.
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the afficheData.
	 * @return String
	 */
	public String getAfficheData() {
		return afficheData;
	}

	/** 
	 * Set the afficheData.
	 * @param afficheData The afficheData to set
	 */
	public void setAfficheData(String afficheData) {
		this.afficheData = afficheData;
	}

	/** 
	 * Returns the afficheTitle.
	 * @return String
	 */
	public String getAfficheTitle() {
		return afficheTitle;
	}

	/** 
	 * Set the afficheTitle.
	 * @param afficheTitle The afficheTitle to set
	 */
	public void setAfficheTitle(String afficheTitle) {
		this.afficheTitle = afficheTitle;
	}

	public String getAfficheContent() {
		return afficheContent;
	}

	public void setAfficheContent(String afficheContent) {
		this.afficheContent = afficheContent;
	}
}